#!/bin/bash

########################################
# helper functions
########################################

# emphasized echo message
empcho() {
    local emph=$(echo -en "\033[7m")
    local norm=$(echo -en "\033[0m")
    local lmark=">>--"
    local rmark="--<<"
    echo -e "$emph$lmark ${@} $rmark$norm"
}

# error handler
# params: $1 = exit code, $2 = optional failed routine name
fatal_error() {
    empcho "$2 failed with code $1"
    exit $1
}

########################################
# main functions
########################################

# deploy current repo state to heroku
heroku_deploy() {
    # login if not logged in
    echo "checking heroku login:"
    heroku auth:whoami || fatal_error $? "heroku login"
    echo

    # add heroku remote if not present
    if [ -z "$(git remote | grep heroku)" ]; then
        heroku git:remote --app vacations-test || fatal_error $? "add heroku git remote"
        echo
    fi

    # some information
    local GIT='git -c color.ui=always'
    cat <<ENDMSG
current branch:
$($GIT branch) 

status:
$($GIT status)

Deploy to heroku? [y/N]
ENDMSG

    # make sure 
    read ans
    if [ "$ans" != 'Y' ] && [ "$ans" != 'y' ]; then
        empcho "aborted."
        exit 2
    fi

    # deploy
    git push heroku master || fatal_error $? "git push to heroku"
    empcho "DEPLOY SUCCESSFUL"
    return 0
}

########################################
# script main body
########################################

# no special arguments so far
heroku_deploy
